# Can override any of this propeties in CLI as follows:
# -Dconfig.override.sequencer.engine-api=http://127.0.0.1:8650

[finalization-signer.web3signer]
endpoint="http://127.0.0.1:9000"

[data-submission-signer.web3signer]
endpoint="http://127.0.0.1:9000"

[l2-signer.web3signer]
endpoint="http://127.0.0.1:9000"

[prover]
fs-requests-directory="tmp/local/prover-execution/v2/requests"
fs-responses-directory="tmp/local/prover-execution/v2/responses"

[blob-compression]
[blob-compression.prover]
fs-requests-directory="tmp/local/prover-compression/v2/requests"
fs-responses-directory="tmp/local/prover-compression/v2/responses"

[proof-aggregation.prover]
fs-requests-directory="tmp/local/prover-aggregation/v2/requests"
fs-responses-directory="tmp/local/prover-aggregation/v2/responses"

[zk-traces]
eth-api="http://127.0.0.1:8645"

# Config of Traces API Facade endpoint
[traces]
[traces.counters]
endpoints=["http://127.0.0.1:8080/"]
[traces.conflation]
endpoints=["http://127.0.0.1:8080/"]
[traces.file-manager]
traces-file-extension = "json.gz"
raw-traces-directory = "tmp/local/traces/raw"
non-canonical-raw-traces-directory = "tmp/local/traces/raw-non-canonical"

[state-manager]
endpoints=["http://127.0.0.1:8998/"]

[dynamic-gas-price-service]
geth-gas-price-update-recipients=[
  "http://127.0.0.1:8645",
  "http://127.0.0.1:8845"
]
besu-gas-price-update-recipients=[
  "http://127.0.0.1:8545/"
]
extra-data-update-recipient="http://127.0.0.1:8545/"

[l1]
rpc-endpoint="http://127.0.0.1:8445"
blocks-to-finalization=2
# blocks are 2s, this may catch in between blocks
send-message-event-polling-interval="PT1S"
# 10 blocks worth at 2s per block
max-event-scraping-time="PT20S"
block-range-loop-limit=10000
finalized-block-tag="finalized"
earliestBlock=0

[l2]
rpc-endpoint="http://127.0.0.1:8645"
blocks-to-finalization=0

[database]
host="localhost"

[api]
observability_port=9546

[type2-state-proof-provider]
endpoints = ["http://127.0.0.1:8889/"]

[conflation]
#switch-block-number=20
